name: Lint, Test and Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install go1.21.5
        uses: actions/setup-go@v5
        with:
          go-version: '^1.21.5'
      - name: Check the go version
        run: go version
