name: Lint, Test and Deploy
on: push
permissions:
  pull-requests: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install go1.21.5
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.5'
      - name: Check the go version
        run: go version
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
  test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install go1.21.5
          uses: actions/setup-go@v5
          with:
            go-version: '1.21.5'
        - name: Check the go version
          run: go version
        - name: Test run
          run: |
            EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
            echo "test_result<<$EOF" >> "$GITHUB_ENV"
            rake test >> "$GITHUB_ENV"
            echo "$EOF" >> "$GITHUB_ENV"
        - uses: marocchino/sticky-pull-request-comment@v2
          with:
            header: test
            append: true
            message: |
              ```
              ${{ env.test_result }}
              ```
  deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Install go1.21.5
          uses: actions/setup-go@v5
          with:
            go-version: '1.21.5'
        - name: Check the go version
          run: go version
        - name: Build the code
          run: go build -o greetings
        - name: Run the code
          run: ./greetings
